services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686" # Web UI
      - "14250:14250"
      #- "6831:6831/udp" # UDP port for Jaeger agent
      #- "14268" # HTTP port for spans
      #- "4317" # OTLP gRPC receiver
      #- "4318" # OTLP http receiver
    command: --collector.otlp.enabled=true --prometheus.server-url=http://prometheus:9090
    environment:
      METRICS_STORAGE_TYPE: "prometheus"
      PROMETHEUS_QUERY_NORMALIZE_CALLS: true
      PROMETHEUS_QUERY_NORMALIZE_DURATION: true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

# De momento comentamos, no necesitamos
#  loki:
#    image: grafana/loki:latest
#    command: -config.file=/mnt/config/loki-config.yml
#    ports:
#      - "3100:3100"
#    volumes:
#      - ./loki-config.yml:/mnt/config/loki-config.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yaml
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana-dashboards:/var/lib/grafana/dashboards
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
#    environment:
#      TMPDIR: /data/tmp/
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /opt/opentelemetry-jmx-metrics.jar:/opt/opentelemetry-jmx-metrics.jar
#      - ./tmp:/data/tmp/
    ports:
      - "4317:4317" # OTLP gRPC receiver
      #- "4318:4318" # OTLP HTTP receiver
      - "1888:1888"   # pprof extension
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
#    extra_hosts:
#    - "host.docker.internal:host-gateway"
    depends_on:
      - jaeger-all-in-one
      - prometheus