global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: 
        #- 'otel-collector:8888'
        - 'otel-collector:8889'
  - job_name: enabler-ws
    static_configs:
      - targets: ["host.docker.internal:9000"]
      - targets: ["host.docker.internal:8100"]
#  - job_name: 'jmx_exporter'
#    metrics_path: ''
#    scrape_interval: 10s
#    static_configs:
#      - targets: ["host.docker.internal:5678"]
#      - targets: ["host.docker.internal:9001"]