global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets:
        #- 'otel-collector:8888'    # Metricas del propio OTEL COLLECTOR.
        - 'otel-collector:8889'
  - job_name: 'prometheus'
    static_configs:
      - targets:
        #- 'otel-collector:8888'    # Metricas del propio OTEL COLLECTOR.
        - 'localhost:8889'
# ACTIVAR ESTO PARA MONITORIZAR LAS METRICAS ANTIGUAS DE PROMETHEUS JMX
#  - job_name: enabler-ws
#    static_configs:
#      - targets: ["host.docker.internal:9000"]
#      - targets: ["host.docker.internal:8100"]