{
 "title": "JMX Overview (OpenTelemetry)",
 "description": "Dashboard for JVM metrics with Prometheus / OpenTelemetry instrumentation",
 "tags": [
  "JVM",
  "JMX",
  "OpenTelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({exported_job=~\"nemergent-backend|nemergent-cms-gms\"},exported_instance)"
    }
   },
   {
    "name": "exported_job",
    "label": "Exported Job*",
    "query": {
     "query": "label_values(target_info{exported_instance=~\"$instance\"},exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "Warning: in a Kubernetes context this data is misleading as it compare against the whole server CPU and not the pod CPU limit. Look at the Kubernetes pod systat dashboard instead.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "CPU utilization (whole system)"
    },
    {
     "expr": "jvm_cpu_recent_utilization_ratio{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "JVM CPU utilization"
    }
   ]
  },
  {
   "title": "Average CPU load of the whole system for the last minute (experimental)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jvm_system_cpu_load_1m{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "Average CPU load"
    }
   ]
  },
  { "title": "Memory pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap memory used / commited / max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\",jvm_memory_type=\"heap\"})",
     "legendFormat": "Heap used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\",jvm_memory_type=\"heap\"})",
     "legendFormat": "Heap committed"
    },
    {
     "expr": "sum(jvm_memory_limit_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\",jvm_memory_type=\"heap\"})",
     "legendFormat": "Heap max obtainable"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "{{ jvm_memory_type }} - {{ jvm_memory_pool_name }}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "{{ jvm_memory_type }} - {{ jvm_memory_pool_name }}"
    }
   ]
  },
  {
   "title": "Max obtainable memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_limit_bytes{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "{{ jvm_memory_type }} - {{ jvm_memory_pool_name }}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Number of executing threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "jvm_thread_count{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "Daemon: {{jvm_thread_daemon}} - State: {{jvm_thread_state}}"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "JVM garbage collection duration - end of minor GC",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "repeat": "gc_action",
   "targets": [
    {
     "expr": "sum(round(rate(jvm_gc_duration_seconds_bucket{exported_instance=~\"$instance\",exported_job=~\"$exported_job\",jvm_gc_action=\"end of minor GC\"}[$__interval]) * $__interval_ms / 1000)) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "JVM garbage collection duration - end of major GC",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(round(rate(jvm_gc_duration_seconds_bucket{exported_instance=~\"$instance\",exported_job=~\"$exported_job\",jvm_gc_action=\"end of major GC\"}[$__interval]) * $__interval_ms / 1000)) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Number of classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_class_count{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "Currently loaded"
    },
    {
     "expr": "jvm_class_loaded_total{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "Loaded since JVM start"
    },
    {
     "expr": "jvm_class_unloaded_total{exported_instance=~\"$instance\",exported_job=~\"$exported_job\"}",
     "legendFormat": "Unloaded since JVM start"
    }
   ]
  }
 ]
}