{
 "title": "CMS/GMS - Custom metrics",
 "description": "CMS custom metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({exported_job=~\"nemergent-cms-gms\"},exported_instance)"
    }
   },
   {
    "name": "exported_job",
    "label": "Exported Job*",
    "query": {
     "query": "label_values(target_info{exported_instance=~\"$instance\"},exported_job)"
    }
   },
   { "name": "cms_prefix", "label": "cms_prefix", "query": "cms_" }
  ]
 },
 "panels": [
  {
   "title": "Active subscriptions received",
   "type": "stat",
   "description": "Active internal subscriptions in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}received_subscriptions_active{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total subscriptions received",
   "type": "stat",
   "description": "Total number of internal subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}received_subscriptions_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active external subscriptions",
   "type": "stat",
   "description": "Active external subscriptions in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}external_subscriptions_active{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total external subscriptions",
   "type": "stat",
   "description": "Total number of external subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}external_subscriptions_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active document subscriptions",
   "type": "stat",
   "description": "Total number of external subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}document_subscriptions_active{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total document subscriptions",
   "type": "stat",
   "description": "Total number of external subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}document_subscriptions_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active collection subscriptions",
   "type": "stat",
   "description": "Total number of external subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}collection_subscriptions_active{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total collection subscriptions",
   "type": "stat",
   "description": "Total number of external subscriptions created in the current session.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "subs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}collection_subscriptions_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active actors",
   "type": "stat",
   "description": "Active actors in the current CMS session.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}actors_active{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total actors",
   "type": "stat",
   "description": "Total number of active actors in the current CMS session.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${cms_prefix}actors_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}