{
 "title": "OAM Backend - Custom metrics",
 "description": "OAM Backend custom metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({exported_job=~\"nemergent-backend\"},exported_instance)"
    }
   },
   {
    "name": "exported_job",
    "label": "Exported Job*",
    "query": {
     "query": "label_values(target_info{exported_instance=~\"$instance\"},exported_job)"
    }
   },
   { "name": "backend_prefix", "label": "backend_prefix", "query": "backend_" }
  ]
 },
 "panels": [
  {
   "title": "Successful logins",
   "type": "stat",
   "description": "The total number of OAM User that has logged in successfully.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${backend_prefix}successful_logins_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login attempts",
   "type": "stat",
   "description": "The total number of logins that have been attempted.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${backend_prefix}login_attempts_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login failure rate",
   "type": "stat",
   "description": "Percentage of failure rate of login attempts.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (clamp_min(${backend_prefix}successful_logins_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}, 1) / clamp_min(${backend_prefix}login_attempts_total{exported_instance=\"$instance\", exported_job=\"$exported_job\"}, 1))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}