{
 "title": "98 - JVM dashboard - Homer 192.168.1.4 (Original)",
 "description": "java.lang metrics dashboard",
 "tags": [
  "Java",
  "JVM"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(jmx_exporter_build_info{job=\"$job\"})"
    }
   },
   { "name": "job", "label": "JOB", "query": "jmx_exporter" }
  ]
 },
 "panels": [
  {
   "title": "OS Load average",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS Used RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"} - java_lang_OperatingSystem_FreePhysicalMemorySize{instance=\"$instance\"}) / java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "OS Used Swap",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_TotalSwapSpaceSize{instance=\"$instance\"} - java_lang_OperatingSystem_FreeSwapSpaceSize{instance=\"$instance\"}) / java_lang_OperatingSystem_TotalSwapSpaceSize{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Used Non-Heap",
   "type": "stat",
   "description": "Used Non-Heap is not gauge because I don't have treshold",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Non-Heap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Metaspace usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_commited{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "PS Old Gen usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"PS Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"PS Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Classs Space usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Cache usage",
   "type": "graph",
   "description": "Only Java < 9",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - Profiled NMethods usage",
   "type": "graph",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - Profiled NMethods usage",
   "type": "graph",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - Non-NMethods usage",
   "type": "graph",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Young generation - Memory Before / After GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used{instance=\"$instance\"})",
     "legendFormat": "Before"
    },
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_used{instance=\"$instance\"})",
     "legendFormat": "After"
    },
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used{instance=\"$instance\"}) - sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_used{instance=\"$instance\"})",
     "legendFormat": "Collected"
    }
   ]
  },
  {
   "title": "G1 Young generation - Collection count vs duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_CollectionCount{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_CollectionCount{instance=\"$instance\"}",
     "legendFormat": "Collection count"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_duration{instance=\"$instance\"}",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "G1 Young generation - Last GC thread count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_GcThreadCount{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_GcThreadCount{instance=\"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_PeakThreadCount{instance=\"$instance\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "java_lang_Threading_ThreadCount{instance=\"$instance\"}",
     "legendFormat": "Non-Daemon"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{instance=\"$instance\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Current Thread CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTime{instance=\"$instance\"}",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ClassLoading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_ClassLoading_TotalLoadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Total loaded"
    },
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Currently loaded"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Unloaded"
    }
   ]
  },
  {
   "title": "Compilation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total compilation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "java_lang_Compilation_TotalCompilationTime{instance=\"$instance\"}",
     "legendFormat": "Total compilation time"
    }
   ]
  },
  {
   "title": "Compilation time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(java_lang_Compilation_TotalCompilationTime{instance=\"$instance\"}[40s])",
     "legendFormat": "Total compilation time"
    }
   ]
  },
  {
   "title": "Operating system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{instance=\"$instance\"}",
     "legendFormat": "Opened"
    },
    {
     "expr": "java_lang_OperatingSystem_MaxFileDescriptorCount{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "OS Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{instance=\"$instance\"}",
     "legendFormat": "Commited Virtual Memory"
    },
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": "Total Physical Memory"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    }
   ]
  }
 ]
}