{
 "title": "JVM dashboard - Import by ID",
 "description": "java.lang metrics dashboard",
 "tags": [
  "Java",
  "JVM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(jmx_exporter_build_info{job=\"$job\"})"
    }
   },
   { "name": "job", "label": "JOB", "query": "otel-collector" },
   { "name": "range", "label": "Range", "query": "1m,5m,10m,15m,30m,1h,2h,3h,6h" }
  ]
 },
 "panels": [
  {
   "title": "OS Load average",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS Used RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"} - java_lang_OperatingSystem_FreePhysicalMemorySize{instance=\"$instance\"}) / java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "OS Used Swap",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_TotalSwapSpaceSize{instance=\"$instance\"} - java_lang_OperatingSystem_FreeSwapSpaceSize{instance=\"$instance\"}) / java_lang_OperatingSystem_TotalSwapSpaceSize{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Used Non-Heap",
   "type": "stat",
   "description": "Used Non-Heap is not gauge because I don't have treshold",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Non-Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "(avg_over_time(java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"}[$range]) AND java_lang_Memory_NonHeapMemoryUsage_max{instance=\"$instance\"} > 0 OR java_lang_Memory_NonHeapMemoryUsage_max{instance=\"$instance\"} > bool 0) / java_lang_Memory_NonHeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "(avg_over_time(java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"}[$range]) AND java_lang_Memory_HeapMemoryUsage_max{instance=\"$instance\"} > 0 OR java_lang_Memory_HeapMemoryUsage_max{instance=\"$instance\"} > bool 0) / java_lang_Memory_HeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Metaspace usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_commited{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Metaspace\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_Metaspace_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "((avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Metaspace\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_Metaspace_Usage_used{instance=\"$instance\"}[$range])) AND (java_lang_MemoryPool_Usage_max{name=\"Metaspace\",instance=\"$instance\"} > 0 OR java_lang_Metaspace_Usage_max{instance=\"$instance\"} > 0) OR (java_lang_MemoryPool_Usage_max{name=\"Metaspace\",instance=\"$instance\"} > bool 0 OR java_lang_Metaspace_Usage_max{instance=\"$instance\"} > bool 0)) / java_lang_MemoryPool_Usage_max{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Metaspace\",instance=\"$instance\"} OR java_lang_Metaspace_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Old Gen usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"G1 Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"G1 Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_MemoryPool_Usage_used{name=\"G1 Old Gen\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_G1_Old_Gen_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "((avg_over_time(java_lang_MemoryPool_Usage_used{name=\"G1 Old Gen\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_G1_Old_Gen_Usage_used{instance=\"$instance\"}[$range])) AND (java_lang_MemoryPool_Usage_max{name=\"G1 Old Gen\",instance=\"$instance\"} > 0 OR java_lang_G1_Old_Gen_Usage_max{instance=\"$instance\"} > 0) OR (java_lang_MemoryPool_Usage_max{name=\"G1 Old Gen\",instance=\"$instance\"} > bool 0 OR java_lang_G1_Old_Gen_Usage_max{instance=\"$instance\"} > bool 0)) / (java_lang_MemoryPool_Usage_max{name=\"G1 Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_max{instance=\"$instance\"})",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"G1 Old Gen\",instance=\"$instance\"} OR java_lang_G1_Old_Gen_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Classs Space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_Compressed_Class_Space_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "((avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\",instance=\"$instance\"}[$range]) OR avg_over_time(java_lang_Compressed_Class_Space_Usage_used{instance=\"$instance\"}[$range])) AND (java_lang_MemoryPool_Usage_max{name=\"Compressed Class Space\",instance=\"$instance\"} > 0 OR java_lang_Compressed_Class_Space_Usage_max{instance=\"$instance\"} > 0 ) OR java_lang_MemoryPool_Usage_max{name=\"Compressed Class Space\",instance=\"$instance\"} > bool 0 OR java_lang_Compressed_Class_Space_Usage_max{instance=\"$instance\"} > bool 0) / (java_lang_MemoryPool_Usage_max{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_max{instance=\"$instance\"})",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Compressed Class Space\",instance=\"$instance\"} OR java_lang_Compressed_Class_Space_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Cache usage",
   "type": "timeseries",
   "description": "Only Java < 9",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Code Cache\",instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "(((avg_over_time(java_lang_MemoryPool_Usage_used{name=\"Code Cache\",instance=\"$instance\"}[$range]) AND java_lang_MemoryPool_Usage_max{name=\"Code Cache\",instance=\"$instance\"} > 0) OR java_lang_MemoryPool_Usage_max{name=\"Code Cache\",instance=\"$instance\"} > bool 0)) / java_lang_MemoryPool_Usage_max{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_max{name=\"Code Cache\",instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - Profiled NMethods usage",
   "type": "timeseries",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_CodeHeap_profiled_nmethods_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "(avg_over_time(java_lang_CodeHeap_profiled_nmethods_Usage_used{instance=\"$instance\"}[$range]) AND java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"} > 0 OR java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"} > bool 0) / java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - NonProfiled NMethods usage",
   "type": "timeseries",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_CodeHeap_non_profiled_nmethods_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "((avg_over_time(java_lang_CodeHeap_non_profiled_nmethods_Usage_used{instance=\"$instance\"}[$range]) AND java_lang_CodeHeap_non_profiled_nmethods_Usage_max{instance=\"$instance\"} > 0) OR java_lang_CodeHeap_non_profiled_nmethods_Usage_max{instance=\"$instance\"} > bool 0) / java_lang_CodeHeap_non_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Heap - Non-NMethods usage",
   "type": "timeseries",
   "description": "Only Java 9+",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_committed{instance=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_used{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(java_lang_CodeHeap_non_nmethods_Usage_used{instance=\"$instance\"}[$range])",
     "legendFormat": "Used (avg $range)"
    },
    {
     "expr": "(avg_over_time(java_lang_CodeHeap_non_nmethods_Usage_used{instance=\"$instance\"}[$range]) AND java_lang_CodeHeap_non_nmethods_Usage_max{instance=\"$instance\"} > 0 OR java_lang_CodeHeap_non_nmethods_Usage_max{instance=\"$instance\"} > bool 0) / java_lang_CodeHeap_non_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Used (avg $range in %)"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Young generation - Memory Before / After GC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used{instance=\"$instance\"})",
     "legendFormat": "Before"
    },
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_used{instance=\"$instance\"})",
     "legendFormat": "After"
    },
    {
     "expr": "sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageBeforeGc_used{instance=\"$instance\"}) - sum(java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_memoryUsageAfterGc_used{instance=\"$instance\"})",
     "legendFormat": "Collected"
    }
   ]
  },
  {
   "title": "G1 Young generation - Collection count vs duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(java_lang_GarbageCollector_CollectionCount{name=\"G1 Young Generation\",instance=\"$instance\"}[$range]) OR rate(java_lang_G1_Young_Generation_CollectionCount{instance=\"$instance\"}[$range])",
     "legendFormat": "Collection count"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration{name=\"G1 Young Generation\",instance=\"$instance\"} OR java_lang_G1_Young_Generation_LastGcInfo_duration{instance=\"$instance\"}",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_Threading_PeakThreadCount{instance=\"$instance\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "java_lang_Threading_ThreadCount{instance=\"$instance\"}",
     "legendFormat": "Non-Daemon"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{instance=\"$instance\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Current Thread CPU time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTime{instance=\"$instance\"}",
     "legendFormat": "Time"
    },
    {
     "expr": "avg_over_time(java_lang_Threading_CurrentThreadCpuTime{instance=\"$instance\"}[$range])",
     "legendFormat": "Time (avg $range)"
    }
   ]
  },
  {
   "title": "ClassLoading, Compilation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ClassLoading",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_ClassLoading_TotalLoadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Total loaded"
    },
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Currently loaded"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{instance=\"$instance\"}",
     "legendFormat": "Unloaded"
    }
   ]
  },
  {
   "title": "Compilation time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "java_lang_Compilation_TotalCompilationTime{instance=\"$instance\"}",
     "legendFormat": "Total compilation time"
    },
    {
     "expr": "irate(java_lang_Compilation_TotalCompilationTime{instance=\"$instance\"}[$range])",
     "legendFormat": "Compilation time rate"
    }
   ]
  },
  {
   "title": "Operating system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OS Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{instance=\"$instance\"}",
     "legendFormat": "Commited Virtual Memory"
    },
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": "Total Physical Memory"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{instance=\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{instance=\"$instance\"}",
     "legendFormat": "Opened"
    },
    {
     "expr": "java_lang_OperatingSystem_MaxFileDescriptorCount{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}